spring:
  cloud:
    function:
      definition: ''
    stream:
      bindings: {}
      binders:
        solace-binder:
          type: solace
          environment:
            solace:
              java:
                host: tcps://mr-connection-gzlgwqngprp.messaging.solace.cloud:55443
                msgVpn: hr-conf-demo-broker
                clientUsername: solace-cloud-client
                clientPassword: smasb3pqamfrmdgs55it30v4or
logging:
  level:
    root: info
    org:
      springframework: info
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'

